In [1]:
# Import module by Alias

import numpy as np

In [2]:
# Check Version

np.__version__

'1.23.4'

###  Creating Array from python list.

In [3]:
# Array must be enclosed in parenthesis

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [19]:
# Check default int size.

np.array([1,2,3,4]).dtype

dtype('int32')

In [20]:
# Float array.

np.array([1,2.3,3,4])

array([1. , 2.3, 3. , 4. ])

In [22]:
# Check default float size.

np.array([1,2.3,3,4]).dtype

dtype('float64')

In [26]:
# String array. Data type shown by default.

np.array(['a', 'b', 'c'])

array(['a', 'b', 'c'], dtype='<U1')

### Upcast ( Two types 1. Automatic 2. Explicit)

In [4]:
# Automatic Upcast 
np.array([2.5,4, 5, 8.9])

array([2.5, 4. , 5. , 8.9])

In [5]:
# Automatic Upcast
np.array([1, 2, 3.5, 'a', 5])

array(['1', '2', '3.5', 'a', '5'], dtype='<U32')

In [ ]:
# Explicitly set the datatype using `dtype` keyword. Two system `dtype = 'int16'` or `dtype = np.int16`

np.array([1, 2, 3.5, 'a', 5], dtype = np.int16)

In [7]:
np.array([2.5,4, 5, 8.9], dtype = 'int16')

array([2, 4, 5, 8], dtype=int16)

In [ ]:
np.array([2,4,5,6], dtype= 'float32')

### Creating Arrays from Scratch

In [8]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [9]:
np.zeros(10, dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Create a 3x4 floating-point array filled with ones
np.ones((3,4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [11]:
# Create a 3x4 array filled with 2.1416
np.full((3,4), 3.1416)

array([[3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416]])

In [12]:
# Create an array filled with a linear sequence
# using np.arange(start, end, step)
# (this is similar to the built-in range() function)

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
# Create an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
# linespace make arry float by default.
np.linspace(0, 24, 5)

array([ 0.,  6., 12., 18., 24.])

In [29]:
np.random.randint(0, 10, (3, 3))

array([[9, 9, 1],
       [3, 0, 1],
       [3, 9, 6]])

In [32]:
#Identity matrix must be square matrix row colmn same.

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [34]:
# size will be gone in touple .
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [36]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [37]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [38]:
print("x1 number of dimention = ", x1.ndim)
print("x1 shape = ", x1.shape)
print("x1 size = ", x1.size)
print("x1 data type = ", x1.dtype)
print("x1 size (in byte) of each element = ", x1.itemsize, "bytes")
print("x1 total array size(in byte) = ", x1.nbytes, "bytes\n\n")

print("x2 number of dimention = ", x2.ndim)
print("x2 shape = ", x2.shape)
print("x2 size = ", x2.size)
print("x2 data type = ", x2.dtype)
print("x2 size (in byte) of each element = ", x2.itemsize, "bytes")
print("x2 total array size(in byte) = ", x2.nbytes, "bytes\n\n")

print("x3 number of dimention = ", x3.ndim)
print("x3 shape = ", x3.shape)
print("x3 size = ", x3.size)
print("x3 data type = ", x3.dtype)
print("x3 size (in byte) of each element = ", x3.itemsize, "bytes")
print("x3 total array size(in byte) = ", x3.nbytes, "bytes")

x1 number of dimention =  1
x1 shape =  (6,)
x1 size =  6
x1 data type =  int32
x1 size (in byte) of each element =  4 bytes
x1 total array size(in byte) =  24 bytes


x2 number of dimention =  2
x2 shape =  (3, 4)
x2 size =  12
x2 data type =  int32
x2 size (in byte) of each element =  4 bytes
x2 total array size(in byte) =  48 bytes


x3 number of dimention =  3
x3 shape =  (3, 4, 5)
x3 size =  60
x3 data type =  int32
x3 size (in byte) of each element =  4 bytes
x3 total array size(in byte) =  240 bytes


In [39]:
x1

array([5, 0, 3, 3, 7, 9])

In [40]:
x1[0]

5

In [41]:
x1[-1]

9

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x2[0]

array([3, 5, 2, 4])

In [44]:
x2[1,2]

8

In [46]:
x2[0, -1]

4

In [49]:
x2[0, 0] = 9
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [50]:
x2[0, 0] = 2.1416
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [51]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x[:5]

array([0, 1, 2, 3, 4])

In [53]:
# perstape gap (step-1)
x[::3]

array([0, 3, 6, 9])

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [56]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [60]:
print(x2)
x2[0, 0]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


2

In [59]:
print(x2)
x2[:2, :3]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[2, 5, 2],
       [7, 6, 8]])

In [59]:
print(x2)
x2[::2, :3]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[2, 5, 2],
       [7, 6, 8]])

In [64]:
print(x2)
x2[:, ::-1]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[4, 2, 5, 2],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [65]:
print(x2)
x2[::-1, :]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [2, 5, 2, 4]])

In [66]:
print(x2)
x2[::-1, ::-1]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 2]])

In [68]:
x2

array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [69]:
print(x2)
x2[:, 0]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([2, 7, 1])

In [70]:
print(x2)
x2[0, :]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([2, 5, 2, 4])

In [71]:
print(x2)
x2[0]

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([2, 5, 2, 4])

In [88]:
print(x2)
print('\n')
x2_sub = x2[:2, :2]
print(x2_sub)
print('\n')
print(x2)

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[2 5]
 [7 6]]
[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [89]:
print(x2)
print('\n')
x2_sub[0,0] = 2
print(x2_sub)
x2

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[2 5]
 [7 6]]


array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [94]:
print(x2)
print('\n')
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
x2

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[2 5]
 [7 6]]


array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [98]:
print(x2)
print('\n')
x2_sub_copy[0, 0] = 9
print(x2_sub_copy)
x2

[[2 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[9 5]
 [7 6]]


array([[2, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [102]:
grid = np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [112]:
x.reshape(1, 3)

array([[1, 2, 3]])

In [113]:
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [117]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [118]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [124]:
z = [99, 99, 99]
np.stack([x, y, z], axis = 1)

array([[ 1,  3, 99],
       [ 2,  2, 99],
       [ 3,  1, 99]])

In [120]:
grid = np.array([[1, 2, 3],
 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [122]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [126]:
 x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
 [6, 5, 4]])
# vertically stack the arrays
np.concatenate([x, grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [125]:
 x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [128]:
 x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
 [6, 5, 4]])
# vertically stack the arrays
np.hstack([x, grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)